"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 12, color: "#334155" },
  header: { fontSize: 24, fontWeight: "bold", color: "#0f172a", marginBottom: 20, borderBottom: "2px solid #2563eb", paddingBottom: 10 },
  section: { marginBottom: 20 },
  label: { fontSize: 10, color: "#64748b", textTransform: "uppercase", marginBottom: 4 },
  value: { fontSize: 14, fontWeight: "bold", color: "#0f172a", marginBottom: 12 },
  grid: { flexDirection: "row", justifyContent: "space-between", flexWrap: "wrap" },
  column: { width: "48%" },
  footer: { position: "absolute", bottom: 40, left: 40, right: 40, textAlign: "center", fontSize: 10, color: "#94a3b8", borderTop: "1px solid #e2e8f0", paddingTop: 10 }
});

export const OfferLetter = ({ deal }: { deal: any }) => {
  // SMART LOGIC: Pick the right price based on the deal type
  const finalPrice = deal.financingMethod === "MORTGAGE" 
    ? Number(deal.property.mortgagePrice) 
    : Number(deal.property.cashPrice);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        <Text style={styles.header}>Property Pilot - Offer Letter</Text>
        
        <View style={styles.section}>
          <Text style={{ fontSize: 12, marginBottom: 20 }}>
            This document serves as an official summary of the unit reservation and agreed-upon pricing in Kenya Shillings (KSh).
          </Text>
        </View>

        <View style={styles.grid}>
          <View style={styles.column}>
            <Text style={styles.label}>Prepared For</Text>
            <Text style={styles.value}>{deal.contact.firstName} {deal.contact.lastName}</Text>
            <Text style={{ fontSize: 10, color: "#475569" }}>{deal.contact.email}</Text>
          </View>
          <View style={styles.column}>
            <Text style={styles.label}>Date Generated</Text>
            <Text style={styles.value}>{new Date().toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={{ marginTop: 30, marginBottom: 30, padding: 15, backgroundColor: "#f8fafc", borderRadius: 4 }}>
          <Text style={[styles.label, { marginBottom: 10 }]}>Property Details</Text>
          
          <View style={styles.grid}>
            <View style={styles.column}>
              <Text style={styles.label}>Project</Text>
              {/* FIXED: Uses the new Project Registry relationship */}
              <Text style={styles.value}>{deal.property.project.name}</Text>
            </View>
            <View style={styles.column}>
              <Text style={styles.label}>Unit Number</Text>
              <Text style={styles.value}>{deal.property.unitNumber}</Text>
            </View>
            <View style={styles.column}>
              <Text style={styles.label}>Payment Plan</Text>
              <Text style={styles.value}>{deal.financingMethod}</Text>
            </View>
            <View style={styles.column}>
              <Text style={styles.label}>Agreed Purchase Price</Text>
              {/* FIXED: KSh formatting and dynamic price selection */}
              <Text style={styles.value}>KSh {finalPrice.toLocaleString()}</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Next Steps</Text>
          <Text style={{ fontSize: 11, lineHeight: 1.5 }}>
            1. Review this summary to ensure all unit details and pricing are correct.{"\n"}
            2. Execute the formal Sales Agreement within 7 days.{"\n"}
            3. Submit the required deposit to secure the reservation of Unit {deal.property.unitNumber}.
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by Property Pilot ERP • {new Date().getFullYear()}
        </Text>
        
      </Page>
    </Document>
  );
};