"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 12, color: "#334155" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 30, borderBottom: "2px solid #e2e8f0", paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: "bold", color: "#0f172a" },
  receiptBadgePaid: { backgroundColor: "#dcfce7", color: "#166534", padding: "4 8", borderRadius: 4, fontSize: 10, textTransform: "uppercase", fontWeight: "bold" },
  receiptBadgeRefund: { backgroundColor: "#fee2e2", color: "#991b1b", padding: "4 8", borderRadius: 4, fontSize: 10, textTransform: "uppercase", fontWeight: "bold" },
  section: { marginBottom: 20 },
  label: { fontSize: 10, color: "#64748b", textTransform: "uppercase", marginBottom: 4 },
  value: { fontSize: 14, fontWeight: "bold", color: "#0f172a", marginBottom: 12 },
  grid: { flexDirection: "row", justifyContent: "space-between", flexWrap: "wrap" },
  column: { width: "48%" },
  amountBoxPaid: { marginTop: 20, padding: 20, backgroundColor: "#f8fafc", borderRadius: 4, alignItems: "center", border: "1px solid #e2e8f0" },
  amountBoxRefund: { marginTop: 20, padding: 20, backgroundColor: "#fef2f2", borderRadius: 4, alignItems: "center", border: "1px solid #fecaca" },
  amountLabel: { fontSize: 12, color: "#64748b", textTransform: "uppercase", marginBottom: 8 },
  amountValue: { fontSize: 32, fontWeight: "bold", color: "#0f172a" },
  amountValueRefund: { fontSize: 32, fontWeight: "bold", color: "#dc2626" },
  footer: { position: "absolute", bottom: 40, left: 40, right: 40, textAlign: "center", fontSize: 10, color: "#94a3b8", borderTop: "1px solid #e2e8f0", paddingTop: 10 }
});

export const PaymentReceipt = ({ client, entry }: { client: any; entry: any }) => {
  const isRefund = entry.type === "REFUND";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
             <Text style={styles.title}>Property Pilot</Text>
             <Text style={{ fontSize: 10, color: "#64748b", marginTop: 4 }}>Transaction Record</Text>
          </View>
          <View>
            <Text style={isRefund ? styles.receiptBadgeRefund : styles.receiptBadgePaid}>
              {isRefund ? "OFFICIAL REFUND" : "OFFICIAL RECEIPT"}
            </Text>
          </View>
        </View>

        <View style={styles.grid}>
          <View style={styles.column}>
            <Text style={styles.label}>{isRefund ? "Issued To" : "Received From"}</Text>
            <Text style={styles.value}>{client.name}</Text>
            <Text style={{ fontSize: 10, color: "#475569" }}>Client Account</Text>
          </View>
          <View style={styles.column}>
            <Text style={styles.label}>Transaction Details</Text>
            <Text style={{ fontSize: 10, marginBottom: 4 }}>Date: {new Date(entry.createdAt).toLocaleDateString()}</Text>
            <Text style={{ fontSize: 10, marginBottom: 4 }}>Ref: {entry.reference || "N/A"}</Text> 
            <Text style={{ fontSize: 10 }}>ID: {entry.id.split('-')[0].toUpperCase()}</Text>
          </View>
        </View>

        <View style={[styles.section, { marginTop: 30 }]}>
          <Text style={styles.label}>{isRefund ? "Refund Applied Against" : "Payment Applied To"}</Text>
          <Text style={styles.value}>Unit {client.unit} • {client.projectName}</Text>
        </View>

        <View style={isRefund ? styles.amountBoxRefund : styles.amountBoxPaid}>
          <Text style={styles.amountLabel}>{isRefund ? "Amount Refunded" : "Amount Paid"}</Text>
          <Text style={isRefund ? styles.amountValueRefund : styles.amountValue}>
             {isRefund ? "- " : ""}KSh {Number(entry.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by Property Pilot ERP • {new Date().getFullYear()} • System-generated document.
        </Text>
      </Page>
    </Document>
  );
};